use_default_settings: true
server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "verysecretkey123456789"
search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json
external_requests:
  proxies:
    http:
    https:
  verify: true
  timeout: 20.0
outgoing:
  request_timeout: 20.0
enabled_engines:
  - google
  - bing
  - duckduckgo
  - brave
  - wikipedia
  - wikidata
